language: c
compiler: gcc
dist: bionic
before_install:
  - sudo apt-get install git lcov uuid-runtime
script:
    - autoreconf -fi && ./configure --enable-code-coverage && make check || cat test/test-suite.log
jobs:
    include:
        -   stage: Code Coverage
            after_success:
                - cd src/
                - bash <(curl -s https://codecov.io/bash)
